package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("хх тест 2")
    void generatedTest() {
        step("открыть https://spb.hh.ru/vacancy/48204083?query=QA%20engineer&from=vacancy_search_catalog&hhtmFrom=vacancy_search_catalog", () -> {
            step("// todo: just add selenium action");
        });

        step("Показать описание вакансии клик", () -> {
            step("// todo: just add selenium action");
        });

        step("найти текст Java", () -> {
            step("// todo: just add selenium action");
        });

        step("не найти Piton", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://spb.hh.ru/vacancy/48204083?query=QA%20engineer&from=vacancy_search_catalog&hhtmFrom=vacancy_search_catalog'", () ->
            open("https://spb.hh.ru/vacancy/48204083?query=QA%20engineer&from=vacancy_search_catalog&hhtmFrom=vacancy_search_catalog"));

        step("Page title should have text 'Вакансия QA Engineer (Automation+Manual) в Санкт-Петербурге, работа в компании ЦРПТ (Центр развития перспективных технологий) (вакансия в архиве c 20 мая 2022)'", () -> {
            String expectedTitle = "Вакансия QA Engineer (Automation+Manual) в Санкт-Петербурге, работа в компании ЦРПТ (Центр развития перспективных технологий) (вакансия в архиве c 20 мая 2022)";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://spb.hh.ru/vacancy/48204083?query=QA%20engineer&from=vacancy_search_catalog&hhtmFrom=vacancy_search_catalog'", () ->
            open("https://spb.hh.ru/vacancy/48204083?query=QA%20engineer&from=vacancy_search_catalog&hhtmFrom=vacancy_search_catalog"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}